server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp # kafka rocketMQ
  canalServerHost: 172.18.100.41:11111
#  zookeeperHosts: slave1:2181
#  mqServers: 127.0.0.1:9092 #or rocketmq
  #是否已flatMessage模式传输,只适用于mq模式
#  flatMessage: true
  #批大小
  batchSize: 500
  #同步分批提交大小,分批次进行同步，一批同步数量为syncBatchSize配置的1000
  syncBatchSize: 1000
  #重试次数
  retries: 0
  #消费超时时间
  timeout:
  # aliyun ak/sk
  accessKey:
  secretKey:
  ##rabbitmq 账号密码
  username:
  password:
  #rabbitmq vhost 默认 /
  vhost:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://172.18.100.57:3306/pcloud_test?useUnicode=true
      username: canal
      password: canal
  canalAdapters:
    - instance: 57test # canal instance Name or mq topic name
      groups:  #组间适配器并行运行
        - groupId: g1 #对应MQ模式下的groupId, 只会同步对应groupId的数据
          outerAdapters: # 组内适配器串行运行，尽量不要配置组内适配器
            - name: logger
            - name: rdb                                               # 指定为rdb类型同步
              key: postgres1                                            # 指定adapter的唯一key, 与表映射配置中outerAdapterKey对应
              properties:
                jdbc.driverClassName: org.postgresql.Driver        # jdbc驱动名, 部分jdbc的jar包需要自行放致lib目录下
                jdbc.url: jdbc:postgresql://172.18.100.39:5432/pcloud?currentSchema=pcloud        # jdbc url
                jdbc.username: postgres                                # jdbc username
                jdbc.password: postgres                                # jdbc password
                threads: 5                                            # 并行执行的线程数, 默认为1
                skipDupException: true
        - groupId: g2 #对应MQ模式下的groupId, 只会同步对应groupId的数据
          outerAdapters: # 组内适配器串行运行，尽量不要配置组内适配器
            - name: logger
            - name: rdb                                               # 指定为rdb类型同步
              key: mysql1                                            # 指定adapter的唯一key, 与表映射配置中outerAdapterKey对应
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver        # jdbc驱动名, 部分jdbc的jar包需要自行放致lib目录下
                jdbc.url: jdbc:mysql://172.18.100.218:3306/pcloud_fs?useUnicode=true        # jdbc url
                jdbc.username: pcloud                                # jdbc username
                jdbc.password: pcloud                                # jdbc password
                threads: 5                                            # 并行执行的线程数, 默认为1
                skipDupException: true
#  canalAdapters:
#  - instance: 57test # canal instance Name or mq topic name
#    groups:
#    - groupId: g1
#      outerAdapters:
#      - name: logger
#      - name: rdb
#        key: mysql1
#        properties:
#          jdbc.driverClassName: com.mysql.jdbc.Driver
#          jdbc.url: jdbc:mysql://127.0.0.1:3306/mytest2?useUnicode=true
#          jdbc.username: root
#          jdbc.password: 121212
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@localhost:49161:XE
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#          threads: 1
#          commitSize: 3000
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
#      - name: es
#        hosts: 127.0.0.1:9300 # 127.0.0.1:9200 for rest mode
#        properties:
#          mode: transport # or rest
#          # security.auth: test:123456 #  only used for rest mode
#          cluster.name: elasticsearch


